LARAVEL/routes/web.php
Route::get('ffmpeg', 'TesteController@ffmpeg');

Route::get('/totem', function () {
    return redirect('https://www.sistemapcb.com.br/public/totem/');
});

Route::get('/', function () {
    Session::forget('id_unidade');
    return view('auth/login');
})->middleware('guest')->name('admin.index');

Route::get('/acesso_negado_dono', function () {
    Session::forget('id_unidade');
    return view('acesso_negado_dono');
});

Auth::routes();

Route::get('novo-usuario', 'Auth\NewUserController@welcome')->name('new-user');
// Route::get('tokenexpired', 'Auth\NewUserController@tokenexpired')->name('tokenexpired');

Route::post('novo-usuario', 'Auth\NewUserController@createPassword')->name('createPassword');
Route::get('password/app/reset', 'Auth\ForgotPasswordController@showResetAppPasswordForm')->name('show-reset-app-password');
Route::post('password/app/reset', 'Auth\ForgotPasswordController@resetAppPassword')->name('reset-app-password');

Route::get('/home', 'HomeController@index');
Route::get('/apps', 'HomeController@apps');

// BACKUP
Route::get('/backup/{senha}', 'Backup\BackupController@backup');
Route::get('/lp/{cliente}', 'LpsController@lp');
Route::get('/lpadmin', 'LpsController@index');

################ INICIO DA ADMINMASTER ################
// CADASTRO LEAD
Route::get('/form_lead', 'AdminMasterController@form_lead');
Route::get('/parabens_lead/{id}', 'AdminMasterController@parabens_lead');
Route::post('/cadastrar_lead', 'AdminMasterController@cadastrar_lead');

Route::get('/form_lead2', 'AdminMasterController@form_lead2');
Route::get('/parabens_lead2/{id}', 'AdminMasterController@parabens_lead2');
Route::post('/cadastrar_lead2', 'AdminMasterController@cadastrar_lead2');
Route::get('/bloqueiaTrial', 'AdminMasterController@bloqueiaTrial');
Route::get('/bloqueiaTrialModulo', 'AdminMasterController@bloqueiaTrialModulo');

Route::group(['prefix' => 'adminmaster', 'middleware' => ['auth', 'adminmasteraccess'], 'as' => 'adminmaster.'], function () {

    Route::get('/', 'AdminMasterController@index');
    Route::get('/empresas', 'AdminMaster\EmpresasController@index');

    Route::post('/addMatriz', 'AdminMasterController@addMatriz');

    Route::post('/addAdminMatriz', 'EmpresasController@addAdminMatriz');

    Route::post('/upAdminMatriz', 'EmpresasController@upAdminMatriz');
    Route::post('/getEmpresas', 'EmpresasController@getEmpresas');
    Route::post('/mudaStatus', 'EmpresasController@mudaStatus');
    Route::post('/mudaLicenca', 'EmpresasController@mudaLicenca');

    Route::post('/upMatriz', 'AdminMasterController@upMatriz');
    Route::get('/getMatriz/{id}', 'AdminMasterController@getMatriz');
});



################ FIM DA ADMINMASTER ################
#
#
#
#
#
#
#
#









#
#
############################################
################ INICIO DA ADMIN NORMAL ################
// depois te q fazer um midware para validar se está logado
Route::group(['prefix' => 'admin', 'middleware' => ['adminaccess'], 'as' => 'admin.'], function () {

    Route::get('/', 'HomeController@homeAdmin');
    Route::get('/passos', 'HomeController@passos');
    Route::get('/passos/parabens', 'HomeController@passosparabens');

// trial
    Route::get('/trial', 'HomeController@trial');


// changeEmp
    Route::get('/changeEmp/{id_unidade}', 'EmpresaController@changeEmp');

    Route::group(['prefix' => 'clube', 'as' => 'clube.'], function () {
        Route::get('/', ['as' => 'index', 'uses' => 'ClubeVantagensController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'ClubeVantagensController@create']);
        Route::get('/edit', ['as' => 'edit', 'uses' => 'ClubeVantagensController@create']);
    });

    // cores app
    Route::group(['prefix' => 'coresApp'], function () {
        Route::get('/{tela?}', 'coresAppController@index');
    });

    // PUSH
    Route::group(['prefix' => 'push'], function () {

        Route::get('/', 'PushController@index');
    });

    // AGENDAMENTO
    Route::group(['prefix' => 'agendamento'], function () {

        Route::get('/', 'AgendamentoController@index');
        // CALENDARIO
        Route::post('/getCaledario', 'AgendamentoController@getCaledario');
        Route::post('/gravaCalendario', 'AgendamentoController@gravaCalendario');
    });

    // CRM
    Route::group(['prefix' => 'crm'], function () {

        Route::get('/', 'CrmController@index');
        Route::get('/operacional', 'CrmController@operacional');
    });

    Route::post('/insere', 'ExercicioController@insere');
    Route::post('/atualiza', 'ExercicioController@atualiza');

    // GENESSON
    // PRESCRIÇÃO
    Route::group(['prefix' => 'prescricao', 'as' => 'prescricao.'], function () {
        Route::get('/nova', ['as' => 'prescricao.index', 'uses' => 'PrescricaoController@index']);

        Route::get('/nova/{id}/{tipo?}', ['as' => 'prescricao.index', 'uses' => 'PrescricaoController@indexId']);
        Route::post('/nova/{id}', ['as' => 'prescricao.index', 'uses' => 'PrescricaoController@indexIdPost']);
        Route::get('/configuracoes', ['as' => 'prescricao.index', 'uses' => 'PrescricaoController@configuracoes']);
        Route::get('/treinopadrao', ['as' => 'prescricao.index', 'uses' => 'PrescricaoController@treinopadrao']);

        // CRUD EXERCICIOS
        Route::post('/insere', 'ExercicioController@insere');
        Route::post('/atualiza', 'ExercicioController@atualiza');
        Route::get('/getExercicios', 'ExercicioController@getExercicios');
        Route::get('/getExerciciosBusca/{busca}', 'ExercicioController@getExerciciosBusca');

        Route::post('/deleteExercicio/{id}', 'ExercicioController@deleteExercicio');
        Route::post('/gerarMiniatura', 'ExercicioController@gerarMiniatura');

        ///insere nivel habilidade
        Route::post('/addNivel', 'NivelhabilidadeController@addNivel');
        Route::post('/upNivel', 'NivelhabilidadeController@upNivel');
        Route::post('/deleteNivel/{id}', 'NivelhabilidadeController@deleteNivel');
        Route::get('/getNiveis/{id}', 'NivelhabilidadeController@getNiveis');
        Route::get('/getModalidades', 'EmpresaController@getModalidades'); // modalidades para incluir niveis
        //insere objetivo de treino
        Route::post('/addObjetivo', 'ObjetivotreinoController@addObjetivo');
        Route::post('/upObjetivo', 'ObjetivotreinoController@upObjetivo');
        Route::get('/getObjetivos/{id}', 'ObjetivotreinoController@getObjetivos'); // modalidades para incluir niveis
        Route::get('/getObjetivo/{id}', 'ObjetivotreinoController@getObjetivo'); // modalidades para incluir niveis
        Route::post('/deleteObjetivo/{id}', 'ObjetivotreinoController@deleteObjetivo');

        //insere objetivo de treino
        Route::post('/addHabilidade', 'NivelhabilidadeController@addHabilidade');
        Route::get('/getHabilidadeAluno/{id}/{nivel}', 'NivelhabilidadeController@getHabilidadeAluno'); // modalidades para incluir niveis
        Route::get('/getHabilidade/{id}', 'NivelhabilidadeController@getHabilidade'); // modalidades para incluir niveis
        Route::get('/delHabilidade/{id}', 'NivelhabilidadeController@delHabilidade'); // modalidades para incluir niveis

        Route::get('/getProcessos', 'ProcessoController@getProcessos'); // processos
        Route::post('/upProcesso', 'ProcessoController@upProcesso'); // processos
        
        
        Route::get('/addHabilidade/{id}', 'NivelhabilidadeController@delHabilidade'); // modalidades para incluir niveis

        Route::post('/addHabilidadeAluno', 'NivelhabilidadeController@addHabilidadeAluno');

//programa treinamento
        Route::post('/addProgramatreinamento', 'ProgramatreinamentoController@addProgramatreinamento');
        Route::post('/upProgramatreinamento', 'ProgramatreinamentoController@upProgramatreinamento');
        Route::post('/deleteProgramatreinamento/{id}', 'ProgramatreinamentoController@deleteProgramatreinamento');
        Route::post('/addAgenda', 'ProgramatreinamentoController@addAgenda');

        Route::post('/upAgenda', 'ProgramatreinamentoController@upAgenda');
        Route::post('/deleteAgenda/{id}', 'ProgramatreinamentoController@deleteAgenda');

        Route::get('/getProgramasAluno/{idaluno}', 'ProgramatreinamentoController@getProgramasAluno');
        Route::get('/getProgramastreinamento', 'ProgramatreinamentoController@getProgramastreinamento');
        Route::get('/getProgramatreinamento/{id}', 'ProgramatreinamentoController@getProgramatreinamento');
        Route::get('/getAgendasProgramatreinamento/{id}', 'ProgramatreinamentoController@getAgendasProgramatreinamento');
        Route::get('/validaProgramaAberto/{id}', 'ProgramatreinamentoController@validaProgramaAberto');
    });

    // EMPRESAS
    Route::group(['prefix' => 'empresas', 'as' => 'empresas.'], function () {
        Route::get('/', 'EmpresaController@index');
        Route::get('/unidades', 'EmpresaController@index');
    });

    // GFMS
    Route::group(['prefix' => 'gfms', 'as' => 'gfms.'], function () {
        Route::get('/', ['as' => 'gfms.index', 'uses' => 'GfmController@index']);
    });

    // SPMS
    Route::group(['prefix' => 'spms', 'as' => 'spms.'], function () {
        Route::get('/', ['as' => 'spms.index', 'uses' => 'SpmController@index']);
    });

// API
    //
    Route::group(['prefix' => 'api'], function () {

        // API DE UNIDADE
        Route::group(['prefix' => 'unidade'], function () {
            // EMPRESA/UNIDADES
            Route::post('/getEstados', 'EmpresaController@getEstados');
            Route::post('/getCidades', 'EmpresaController@getCidades');

            Route::get('/getEstados', 'EmpresaController@getEstados');
            Route::get('/getCidadesGet/{uf}', 'EmpresaController@getCidadesGet');

            Route::post('/getEmpresa', 'EmpresaController@getEmpresa');
            Route::post('/upEmpresa', 'EmpresaController@upEmpresa');
            Route::post('/upPasso', 'EmpresaController@upPasso');

LARAVEL/resources/views/admin/clube/index.blade.php
@extends('layouts.app')
@section('content')

@push('scripts')
{!! Html::script("js/cvempresaController.js") !!}

@endpush


<div ng-controller="cvempresaController" class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Listagem de {{ $headers['title'] }} com paginação, ordernação e filtro</h5>
					<div class="ibox-tools">
						<a class="collapse-link">
							<i class="fa fa-chevron-up"></i>
						</a>
						
						<a class="close-link">
							<i class="fa fa-times"></i>
						</a>
					</div>
				</div>
				<div class="ibox-content">
					<div class="col-xs-12 col-md-8 pd0">
						<div class="input-group"><span class="input-group-addon"><i class="fa fa-search" aria-hidden="true"></i></span>
						<input type="text" class="form-control" id="filter"
					placeholder="Pesquisar na tabela"> </div>
				</div>
				<div class="col-xs-12 col-md-4 pd0 al-right">
					<a  data-toggle="modal" data-target="#modalNovaEmpresa" class="btn btn-primary"><i class="fa fa-plus-square"></i> Nova Empresa</a>
				</div>
				
				
				
				
				<table class="footable table table-stripped" data-page-size="8" data-filter=#filter>
					<thead>
						<tr>
							<th>Id</th>
							<th style="width: 40%">Empresa</th>
							<th style="width: 15%">Vencimento</th>
							<th style="width: 15%">CNPJ</th>
							<th style="width: 15%">Segmento</th>
							<th style="width: 15%">Perc. Desconto</th>
							<th>Total Vendas</th>
							
							<th> </th>
						</tr>
					</thead>
					<tbody>
						
						<tr ng-repeat="cvempresa in cvempresas | filter:searchText"> 
                                                        <td>@{{ cvempresa.id }}</td>
							<td >@{{ cvempresa.nmempresa }}</td>
							<td >@{{ cvempresa.vencimento }}</td>
							<td >@{{ cvempresa.cnpj }}</td>
							<td >@{{ cvempresa.nmsegmento }}</td>
							<td >@{{ cvempresa.percdesconto }} %</td>
							<td >@{{ cvempresa.totalvendas }}</td>
							
							
							<td>
								<!--{{--  href="{{route('admin.clube.edit', $compra->id)}}"  --}}
								<a data-toggle="modal" alt="Editar"  ng-click="select(cvempresa)" style="margin-right: 15px" >
								<i class="fa fa-pencil" style="color: #333"></i> </a>
								<a href="#"  alt="Deletar"  ng-click="destroy(cvempresa)"><i class="fa fa-trash" style="color: #333"></i></a>-->
                                                            <button  class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalEditarCvempresa" ng-click="editCvempresa(cvempresa.id)">
								<i class="fa fa-edit"></i>
                                 			    </button>
                                                            <button class="btn btn-danger btn-sm" ng-click="deleteCvempresa(cvempresa.id)">
								<i class="fa fa-trash"></i>
                                                            </button>                                                                
							</td>
							
						</tr>
						
						
					</tbody>
					<tfoot>
					<tr>
						<td colspan="5">
						<ul class="pagination pull-right"></ul>
					</td>
				</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
@include('admin.clube.modal')    
</div>
@endsection
@section('css')
	{!! Html::style("assets_admin/vendor/pnotify/pnotify.custom.css") !!}
	{!! Html::style("assets_admin/vendor/select2/select2.css") !!}
	{!! Html::style("assets_admin/vendor/bootstrap-fileupload/bootstrap-fileupload.min.css") !!}
@endsection
@section('scripts')
	{!! HTML::script("assets_admin/vendor/jquery-form/jquery.form.min.js") !!}
	{!! HTML::script("assets_admin/vendor/jquery-validation/jquery.validate.js") !!}
	{!! HTML::script("assets_admin/javascripts/forms/cvempresa.validation.js") !!}
	{!! Html::script("assets_admin/vendor/pnotify/pnotify.custom.js") !!}
	{!! Html::script("assets_admin/vendor/jquery-maskedinput/jquery.maskedinput.min.js") !!}
	{!! Html::script("assets_admin/vendor/select2/select2.js") !!}
	{!! Html::script("assets_admin/vendor/bootstrap-fileupload/bootstrap-fileupload.min.js") !!}
	<script type="text/javascript">
		$(document).ready(function() {
                    
                }
        </script>                
	<script type="text/javascript">
		$(document).ready(function() {
			$('#file-input').on('change', function(evt) {
				var file = evt.target.files[0];
				if(file) {
					$('[name="cvempresa_id"]').removeAttr("disabled");
					$('[name="nmempresa"]').removeAttr("disabled");
					$('[name="cnpj"]').removeAttr("disabled");
					$('[name="percdesconto"]').removeAttr("disabled");

					$("#PostFormCvempresaUp").submit();
				}
			});
			
			$('#cnpj').mask("99.999.999/9999-99");
			$('#cnpj1').mask("99.999.999/9999-99");
			
		});
	</script>
@endsection

LARAVEL/resources/views/admin/clube/modal.blade.php
<div class="modal inmodal fade" id="modalNovaEmpresa" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
				<h4 class="modal-title">Nova empresa</h4>
			</div>
			<form name="PostFormCvempresa" id="PostFormCvempresa" method="post" enctype="multipart/form-data">
				<div class="modal-body">
					<div class="row">
						<div class="col-sm-12">
							<div class="form-group">
								<label>Nome Fantasia:</label>
								<input type="text" class="form-control" id="nmempresa" name="nmempresa">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6">
							<div class="form-group">
								<label>(%) Desconto:</label>
								<input type="text" class="form-control" id="percdesconto" name="percdesconto">
							</div>
						</div>
                                                <div class="col-sm-6">
							<div class="form-group">
								<label>CNPJ:</label>
								<input type="text" class="form-control" id="cnpj" name="cnpj">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6">
                                                    <label>Segmento</label>
                                                        <div class="input-group m-b">
                                                                <select name="idsegmento" class="select2_demo_1 form-control">
									<option value="1">Selecione o segmento</option>
									<option ng-repeat="segmento in segmentos"  value="@{{ segmento.id }}">@{{ segmento.nmsegmento }}</option>	
								</select>
                                                        </div>
                                                </div>                                    
						<div class="col-sm-6">
                                                    <div class="form-group" id="data">
							<label>Data de vencimento:</label>
                                                        <div class="input-group date">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                            <input ng-disabled="value1" type="text" class="form-control" name="dtvencimento">
							</div>
                                                        <div class="checkbox m-r-xs">
                                                            <input type="checkbox" ng-model="value1" value="true" name="value1" id="value1">
                                                            <label for="checkbox">Vencimento indeterminado</label>
                                                        </div>
                                                    </div>
        					</div>                                    
					</div>                                    
					<div class="row load" style="display:none;">
						<div class="col-sm-12">
							<div class="progress progress-striped light active">
								<div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="" aria-valuemin="0" aria-valuemax="100">
									<span class="sr-only"></span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<div class="form-group">
						<button type="submit" name="SendPostForm" id="SendPostForm" value="SendPostForm" class="btn btn-primary pull-right"><i class="fa fa-check"></i> Salvar</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<div class="modal inmodal fade" id="modalEditarCvempresa" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
				<h4 class="modal-title">Editar empresa</h4>
			</div>
			<form name="PostFormCvempresaUp" id="PostFormCvempresaUp" method="post" enctype="multipart/form-data">
				<div class="modal-body">
                                       <div style="display:none;"><input type="text" ng-model="cvempresa.id" name="cvempresa_id" id="cvempresa_id"></div>
					<div class="row">
						<div class="col-sm-12">
							<div class="form-group">
								<label>Nome Fantasia:</label>
								<input type="text" class="form-control" ng-model="cvempresa.nmempresa" name="nmempresa">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6">
							<div class="form-group">
								<label>(%) Desconto:</label>
								<input type="text" class="form-control" ng-model="cvempresa.percdesconto" name="percdesconto">
							</div>
						</div>
                                                <div class="col-sm-6">
							<div class="form-group">
								<label>CNPJ:</label>
								<input type="text" class="form-control" ng-model="cvempresa.cnpj" id="cnpj1" name="cnpj1">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6">
                                                    <label>Segmento</label>
                                                    <div class="input-group m-b">
							<select class="form-control" name="idsegmento" ng-model="cvempresa.idsegmento">
								<option value="1">Selecione o segmento</option>
								<option ng-repeat="segmento in segmentos" value="@{{ segmento.id }}">@{{ segmento.nmsegmento }}</option>	
							</select>
                                                    </div>
        					</div>
						<div class="col-sm-6">
                                                    <div class="form-group" id="data">
							<label>Data de vencimento:</label>
                                                        <div class="input-group date">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                            <input type="text" ng-disabled="value1" class="form-control" name="dtvencimento" ng-model="cvempresa.dtvencimento">
							</div>
                                                        <div class="checkbox m-r-xs">
                                                            <input type="checkbox" ng-model="value1" value="true" name="value1" id="value1">
                                                            <label for="checkbox">Vencimento indeterminado</label>
                                                        </div>
                                                        
                                                    </div>
        					</div>                                    
                                            
					</div>                                        
                                       
					<div class="row load" style="display:none;">
						<div class="col-sm-12">
							<div class="progress progress-striped light active">
								<div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="" aria-valuemin="0" aria-valuemax="100">
									<span class="sr-only"></span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<div class="form-group">
						<button type="submit" name="SendPostForm" id="SendPostForm" value="SendPostForm" class="btn btn-primary pull-right"><i class="fa fa-check"></i> Salvar</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>